name: landbot
description: Landbot unofficial plugin
version: 0.0.1
homepage: https://github.com/rohitsangwan01/Landbot.git
repository: https://github.com/rohitsangwan01/Landbot.git


environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  alfred: ^0.1.5+3
  rxdart: ^0.27.3
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
